name: mod_comp
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=3.7.0
  - ipywidgets=7.7.1
  - jupyterlab=3.4.3
  - librosa=0.9.2
  - matplotlib=3.5.2
  - numpy=1.21.6
  - python=3.10.5
  - scipy=1.8.1
  - sympy=1.10.1
  - pandas=1.5.0
  - pip
  - pip:
    - colorednoise==2.1.0
    - dill==0.3.5.1
    - jax==0.3.15
    - jaxlib==0.3.15
    - diffrax==0.2.1
    - equinox==0.6.0
    - nidaqmx==0.6.3
    - tqdm==4.64.0
    - SciencePlots==1.0.9
    - psutil
